! Definitions file for HTAP-PRM RUN

! Run-Mode: Parameters that affect how htap-prm is configured.
RunParameters_START
  run-mode                           = parametric
  archetype-dir                      = C:/HTAP/archetypes
  unit-costs-db                      = C:/HTAP/HTAPUnitCosts.json
  options-file                       = C:/HTAP/HTAP-options.json
RunParameters_END


! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if an optimization mode is added in the future.
RunScope_START

  archetypes                        = ERS-EX-11774.H2K
  locations                         = NA
  rulesets                          = as-found

RunScope_END

! Parameters controlling the design of the building
Upgrades_START


   Opt-ResultHouseCode  = General

   Opt-ACH         = NA

   Opt-Windows     = NA
   Opt-Skylights   = NA
   Opt-DoorWindows = NA
   Opt-Doors       = NA

   Opt-AboveGradeWall = NA, NC_2x6_r19nom_r16Eff, NC_R-23(eff)_2x6-16inOC_R22-batt+1inFoilFacedPolyiso_poly_vb
   Opt-FloorHeaderIntIns = NA

!  Opt-FoundationWallExtIns     =  NA
!  Opt-FoundationWallIntIns     =  NA
!  Opt-FoundationSlabBelowGrade =  NA
!  Opt-FoundationSlabOnGrade    =  NA
   Opt-H2KFoundation            =  NA



   Opt-ExposedFloor     = NA

   Opt-Ceilings         = NA
   Opt-AtticCeilings    = NA
   Opt-CathCeilings     = NA
   Opt-FlatCeilings     = NA

   Opt-VentSystem       = NA
   Opt-DHWSystem        = NA
   Opt-Heating-Cooling  = NA
   Opt-DWHR             = NA
   Opt-H2K-PV           = NA
   Opt-Baseloads        = NA



Upgrades_END
