! Definitions file for HTAP-PRM RUN

! Run-Mode: Parameters that affect how htap-prm is configured.
RunParameters_START
  run-mode                           = parametric
  archetype-dir                      = C:/HTAP
  unit-costs-db                      = C:/HTAP/HTAPUnitCosts.json
  options-file                       = C:/HTAP/HTAP-options.json
RunParameters_END


! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if an optimization mode is added in the future.
RunScope_START

  archetypes                        = 227NN01552.h2k
  locations                         = HALIFAX
  rulesets                          = as-found

RunScope_END

! Parameters controlling the design of the building
Upgrades_START


   Opt-ResultHouseCode  = General

   Opt-ACH         = NA

   Opt-Windows     = NA
   Opt-Skylights   = NA
   Opt-DoorWindows = NA
   Opt-Doors       = NA

   Opt-AboveGradeWall = NA
   Opt-FloorHeaderIntIns = NA

   Opt-FoundationWallExtIns     =  NA
   Opt-FoundationWallIntIns     =  NA
   Opt-FoundationSlabBelowGrade =  NA
   Opt-FoundationSlabOnGrade    =  NA



   Opt-ExposedFloor     = NA

   Opt-Ceilings         = NA
   Opt-AtticCeilings    = NA
   Opt-CathCeilings     = NA
   Opt-FlatCeilings     = NA

   Opt-VentSystem       = NA
   Opt-DHWSystem        = NA
   Opt-Heating-Cooling  = NA
   Opt-DWHR             = NA
   Opt-H2K-PV           = NA
   Opt-Baseloads        = NA
   Opt-WindowDistribution = Proposed-mid-glazing



Upgrades_END
