"""
Writer for HTAP .run files
"""

from pathlib import Path
from datetime import datetime

from src.models.run_config import RunConfiguration


class RunFileWriter:
    """Writer for .run configuration files"""

    def write_file(
        self,
        config: RunConfiguration,
        output_path: str,
        include_timestamp: bool = True
    ) -> None:
        """
        Write RunConfiguration to .run file

        Args:
            config: RunConfiguration model
            output_path: Output file path
            include_timestamp: Add generation timestamp to header
        """
        content = self.generate_content(config, include_timestamp)

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    def generate_content(
        self,
        config: RunConfiguration,
        include_timestamp: bool = True
    ) -> str:
        """
        Generate .run file content from RunConfiguration

        Args:
            config: RunConfiguration model
            include_timestamp: Add generation timestamp

        Returns:
            .run file content as string
        """
        lines = []

        # Header comments
        if config.comments:
            lines.extend(config.comments)
        else:
            lines.append("! Definitions file for HTAP-PRM RUN")

        if include_timestamp:
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            lines.append(f"! Generated by HTAP Configuration Editor on {timestamp}")

        lines.append("")

        # RunParameters section
        lines.append("! Run-Mode: Parameters that affect how htap-prm is configured.")
        lines.append("RunParameters_START")
        lines.append(
            f"  {'run-mode':<35} = {config.parameters.run_mode.value}"
        )
        lines.append(
            f"  {'archetype-dir':<35} = {config.parameters.archetype_dir}"
        )
        lines.append(
            f"  {'unit-costs-db':<35} = {config.parameters.unit_costs_db}"
        )
        lines.append(
            f"  {'options-file':<35} = {config.parameters.options_file}"
        )
        lines.append("RunParameters_END")
        lines.append("")
        lines.append("")

        # RunScope section
        lines.append(
            "! Parameters controlling archetypes, locations, reference rulesets."
        )
        lines.append("RunScope_START")
        lines.append("")
        lines.append(
            f"  {'archetypes':<35} = {config.scope.archetypes}"
        )
        lines.append(
            f"  {'locations':<35} = {config.scope.locations}"
        )
        lines.append(
            f"  {'rulesets':<35} = {config.scope.rulesets}"
        )
        lines.append("")
        lines.append("RunScope_END")
        lines.append("")

        # Upgrades section
        lines.append("! Parameters controlling the design of the building")
        lines.append("Upgrades_START")
        lines.append("")

        if config.upgrades:
            for opt_type, upgrade in sorted(config.upgrades.items()):
                lines.append(upgrade.to_run_format())
        else:
            lines.append("   ! No upgrades specified")

        lines.append("")
        lines.append("Upgrades_END")

        return "\n".join(lines)


def write_run_file(
    config: RunConfiguration,
    output_path: str,
    include_timestamp: bool = True
) -> None:
    """
    Convenience function to write a .run file

    Args:
        config: RunConfiguration model
        output_path: Output file path
        include_timestamp: Add generation timestamp
    """
    writer = RunFileWriter()
    writer.write_file(config, output_path, include_timestamp)
