! Definitions file for HTAP-PRM RUN

! Run-Mode: Parameters that affect how htap-prm is configured.
RunParameters_START
  run-mode                           = parametric
  archetype-dir                      = C:/HTAP/arch
  unit-costs-db                      = C:/HTAP/HTAPUnitCosts.json
  options-file                       = C:/HTAP/HTAP-options.json
RunParameters_END


! Parameters controlling archetypes, locations, reference rulests. (these will always be
! run in mesh, even if an optimization mode is added in the future.
RunScope_START

  archetypes                        = 227NN01521.h2k
  locations                         = HALIFAX
  rulesets                          = as-found

RunScope_END

! Parameters controlling the design of the building
Upgrades_START

   Opt-ResultHouseCode  = General
   Opt-Specifications   = NBC_Specs_Normal

   Opt-ACH         = NA

   Opt-Windows     = NA
   Opt-DoorWindows = NA
   Opt-Doors       = NA

   Opt-FloorHeaderIntIns = NA

   Opt-FoundationWallExtIns     =  NA
   Opt-FoundationWallIntIns     =  NA
   Opt-FoundationSlabBelowGrade =  NA
!   Opt-FoundationSlabBelowGrade =  NA
   Opt-FoundationSlabOnGrade    =  NA
!   Opt-H2KFoundationSlabCrawl   =  NA
   Opt-ExposedFloor     = NA

   Opt-AtticCeilings    = NA
   Opt-CathCeilings     = NA
   Opt-FlatCeilings     = NA

   Opt-VentSystem       = NA
   Opt-Heating-Cooling  = NA
!   Opt-Heating-Cooling  = NA
!   Opt-Heating-Cooling  = NA

   Opt-H2K-PV           = NA
   Opt-Baseloads        = NBC-Baseloads
   Opt-WindowDistribution = NA
   Opt-Temperatures     = NBC_Temps

! These Opt-* parameters have non-NA defaults and must be specified
  Opt-AboveGradeWall    = NA
  Opt-DHWSystem         = NA
  Opt-DWHR              = NA
  Opt-Skylights         = NA


Upgrades_END
