#!/usr/bin/env python3
"""Run htap-prm.rb on post-sub HOT2000 files that lack AllResults output."""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path
import xml.etree.ElementTree as ET

RUN_TEMPLATE = """! Autogenerated run file for HTAP post-sub execution\n\nRunParameters_START\n  run-mode                           = parametric\n  archetype-dir                      = {archetype_dir}\n  unit-costs-db                      = {unit_costs}\n  options-file                       = {options_file}\nRunParameters_END\n\nRunScope_START\n  archetypes                        = {archetype_name}\n  locations                         = {location}\n  rulesets                          = {ruleset}\nRunScope_END\n\nUpgrades_START\n\n   Opt-ResultHouseCode  = General\n\n   Opt-ACH         = ACH_NBC\n\n   Opt-Windows     = NBC-zone4-window\n   Opt-Skylights   = NA\n   Opt-DoorWindows = NA\n   Opt-Doors       = NA\n\n   Opt-AboveGradeWall = NA\n   Opt-FloorHeaderIntIns = NA\n\n   Opt-FoundationWallExtIns     =  NA\n   Opt-FoundationWallIntIns     =  NA\n   Opt-FoundationSlabBelowGrade =  NA\n   Opt-FoundationSlabOnGrade    =  NA\n\n   Opt-ExposedFloor     = NA\n\n   Opt-Ceilings         = NA\n   Opt-AtticCeilings    = NA\n   Opt-CathCeilings     = NA\n   Opt-FlatCeilings     = NA\n\n   Opt-VentSystem       = NA\n   Opt-DHWSystem        = NA\n   Opt-Heating-Cooling  = NA\n   Opt-DWHR             = NA\n   Opt-H2K-PV           = NA\n   Opt-Baseloads        = NA\n   Opt-WindowDistribution = Reference-9.36\n\nUpgrades_END\n"""


def has_gross_area(path: Path) -> bool:
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError:
        return False
    return root.find(".//AllResults/Results/Other/GrossArea") is not None


def write_run_file(
    project_root: Path,
    archetype_dir: Path,
    archetype_name: str,
    options_path: Path,
    unit_costs_path: Path,
    location: str,
    ruleset: str,
) -> Path:
    content = RUN_TEMPLATE.format(
        archetype_dir=archetype_dir.as_posix(),
        archetype_name=archetype_name,
        options_file=options_path.as_posix(),
        unit_costs=unit_costs_path.as_posix(),
        location=location,
        ruleset=ruleset,
    )
    tmp_dir = project_root / "tmp"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", suffix=".run", delete=False, dir=tmp_dir
    ) as handle:
        handle.write(content)
        run_path = Path(handle.name)
    return run_path


def run_htap(
    prm_path: Path,
    h2k_path: Path,
    options_path: Path,
    unit_costs_path: Path,
    location: str,
    ruleset: str,
) -> int:
    run_file = write_run_file(
        prm_path.parent,
        h2k_path.parent,
        h2k_path.name,
        options_path,
        unit_costs_path,
        location,
        ruleset,
    )
    cmd = [
        "ruby",
        str(prm_path),
        "-r",
        str(run_file),
    ]
    result = subprocess.run(
        cmd,
        cwd=str(prm_path.parent),
        capture_output=True,
        text=True,
        check=False,
    )
    run_file.unlink(missing_ok=True)
    if result.returncode != 0:
        sys.stderr.write(
            f"htap-prm.rb failed for {h2k_path}:\n{result.stderr}\n{result.stdout}\n"
        )
    return result.returncode


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Run htap-prm.rb for post-sub .h2k files missing AllResults",
    )
    parser.add_argument(
        "root",
        nargs="?",
        default=Path.cwd(),
        help="Directory to scan (defaults to current working directory)",
    )
    parser.add_argument(
        "--glob",
        default="file-postsub.h2k",
        help="File glob to locate post-sub files (default: file-postsub.h2k)",
    )
    parser.add_argument(
        "--options",
        default=project_root / "HTAP-options.json",
        help="Path to HTAP options JSON (default: HTAP-options.json in repo root)",
    )
    parser.add_argument(
        "--unit-costs",
        default=project_root / "HTAPUnitCosts.json",
        help="Path to HTAP unit cost database",
    )
    parser.add_argument(
        "--location",
        default="HALIFAX",
        help="Location code to use in generated run files (default: HALIFAX)",
    )
    parser.add_argument(
        "--ruleset",
        default="as-found",
        help="Ruleset name to use in generated run files (default: as-found)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Run even if AllResults already exists",
    )
    args = parser.parse_args()

    root_dir = Path(args.root).resolve()
    options_path = Path(args.options).resolve()
    unit_costs_path = Path(args.unit_costs).resolve()
    prm_path = project_root / "htap-prm.rb"

    if not root_dir.exists():
        sys.stderr.write(f"Directory not found: {root_dir}\n")
        return 1
    if not options_path.exists():
        sys.stderr.write(f"Options file not found: {options_path}\n")
        return 1
    if not unit_costs_path.exists():
        sys.stderr.write(f"Unit costs file not found: {unit_costs_path}\n")
        return 1
    if not prm_path.exists():
        sys.stderr.write(f"htap-prm.rb not found at {prm_path}\n")
        return 1

    files = sorted(root_dir.rglob(args.glob))
    if not files:
        print("No matching .h2k files found.")
        return 0

    total = len(files)
    skipped = 0
    failures = 0

    print(f"Found {total} candidate files under {root_dir}")
    for idx, file_path in enumerate(files, 1):
        relative = file_path.relative_to(root_dir)
        if not args.force and has_gross_area(file_path):
            skipped += 1
            print(f"[{idx}/{total}] skip {relative} (AllResults present)")
            continue
        print(f"[{idx}/{total}] running htap-prm.rb for {relative}")
        code = run_htap(
            prm_path,
            file_path,
            options_path,
            unit_costs_path,
            args.location,
            args.ruleset,
        )
        if code != 0:
            failures += 1
        else:
            print(f"[{idx}/{total}] completed {relative}")

    print(
        f"Done. ran={total - skipped} skipped={skipped} failures={failures}"
    )
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
