/**
 * RunFileParser - Parse and generate .run files
 */
class RunFileParser {
    constructor() {
        this.config = this.getDefaultConfig();
    }

    /**
     * Get default configuration
     */
    getDefaultConfig() {
        return {
            runParameters: {
                runMode: 'parametric',
                archetypeDir: 'C:/HTAP',
                unitCostsDb: 'C:/HTAP/HTAPUnitCosts.json',
                optionsFile: 'C:/HTAP/HTAP-options.json'
            },
            runScope: {
                archetypes: [],
                locations: [],
                rulesets: ['as-found']
            },
            upgrades: {}
        };
    }

    /**
     * Parse .run file content
     */
    parse(fileContent) {
        const config = this.getDefaultConfig();
        const lines = fileContent.split('\n');

        let currentSection = null;

        for (let line of lines) {
            line = line.trim();

            // Skip comments and empty lines
            if (line.startsWith('!') || line === '') {
                continue;
            }

            // Detect section starts
            if (line === 'RunParameters_START') {
                currentSection = 'parameters';
                continue;
            } else if (line === 'RunScope_START') {
                currentSection = 'scope';
                continue;
            } else if (line === 'Upgrades_START') {
                currentSection = 'upgrades';
                continue;
            }

            // Detect section ends
            if (line.endsWith('_END')) {
                currentSection = null;
                continue;
            }

            // Parse line based on current section
            if (currentSection === 'parameters') {
                this.parseParameterLine(line, config);
            } else if (currentSection === 'scope') {
                this.parseScopeLine(line, config);
            } else if (currentSection === 'upgrades') {
                this.parseUpgradeLine(line, config);
            }
        }

        this.config = config;
        return config;
    }

    /**
     * Parse parameter line
     */
    parseParameterLine(line, config) {
        const parts = line.split('=').map(p => p.trim());
        if (parts.length !== 2) return;

        const [key, value] = parts;

        if (key === 'run-mode') {
            config.runParameters.runMode = value;
        } else if (key === 'archetype-dir') {
            config.runParameters.archetypeDir = value;
        } else if (key === 'unit-costs-db') {
            config.runParameters.unitCostsDb = value;
        } else if (key === 'options-file') {
            config.runParameters.optionsFile = value;
        }
    }

    /**
     * Parse scope line
     */
    parseScopeLine(line, config) {
        const parts = line.split('=').map(p => p.trim());
        if (parts.length !== 2) return;

        const [key, value] = parts;

        if (key === 'archetypes') {
            config.runScope.archetypes = value.split(',').map(v => v.trim());
        } else if (key === 'locations') {
            config.runScope.locations = value.split(',').map(v => v.trim());
        } else if (key === 'rulesets') {
            config.runScope.rulesets = value.split(',').map(v => v.trim());
        }
    }

    /**
     * Parse upgrade line
     */
    parseUpgradeLine(line, config) {
        const parts = line.split('=').map(p => p.trim());
        if (parts.length !== 2) return;

        const [key, value] = parts;

        if (key.startsWith('Opt-')) {
            config.upgrades[key] = value.split(',').map(v => v.trim());
        }
    }

    /**
     * Generate .run file content
     */
    generate(config) {
        let content = '';

        // Header comment
        content += '! HTAP-PRM RUN Configuration\n';
        content += '! Generated by HTAP Config Tool\n';
        content += `! Date: ${new Date().toISOString()}\n\n`;

        // RunParameters section
        content += 'RunParameters_START\n';
        content += `  run-mode = ${config.runParameters.runMode}\n`;
        content += `  archetype-dir = ${config.runParameters.archetypeDir}\n`;
        content += `  unit-costs-db = ${config.runParameters.unitCostsDb}\n`;
        content += `  options-file = ${config.runParameters.optionsFile}\n`;
        content += 'RunParameters_END\n\n';

        // RunScope section
        content += 'RunScope_START\n';
        if (config.runScope.archetypes.length > 0) {
            content += `  archetypes = ${config.runScope.archetypes.join(', ')}\n`;
        }
        if (config.runScope.locations.length > 0) {
            content += `  locations = ${config.runScope.locations.join(', ')}\n`;
        }
        if (config.runScope.rulesets.length > 0) {
            content += `  rulesets = ${config.runScope.rulesets.join(', ')}\n`;
        }
        content += 'RunScope_END\n\n';

        // Upgrades section
        content += 'Upgrades_START\n';

        // Sort upgrade keys for consistent output
        const upgradeKeys = Object.keys(config.upgrades).sort();

        for (const key of upgradeKeys) {
            const values = config.upgrades[key];
            if (values && values.length > 0) {
                content += `  ${key} = ${values.join(', ')}\n`;
            }
        }

        content += 'Upgrades_END\n';

        return content;
    }

    /**
     * Get current configuration
     */
    getConfig() {
        return this.config;
    }

    /**
     * Set configuration
     */
    setConfig(config) {
        this.config = config;
    }

    /**
     * Update run parameters
     */
    updateRunParameters(params) {
        this.config.runParameters = { ...this.config.runParameters, ...params };
    }

    /**
     * Update run scope
     */
    updateRunScope(scope) {
        this.config.runScope = { ...this.config.runScope, ...scope };
    }

    /**
     * Update upgrades
     */
    updateUpgrades(upgrades) {
        this.config.upgrades = { ...this.config.upgrades, ...upgrades };
    }

    /**
     * Set upgrade option for a category
     */
    setUpgradeOption(categoryId, options) {
        if (options.length === 0) {
            // Default to NA if nothing selected
            this.config.upgrades[categoryId] = ['NA'];
        } else {
            this.config.upgrades[categoryId] = options;
        }
    }

    /**
     * Get upgrade options for a category
     */
    getUpgradeOptions(categoryId) {
        return this.config.upgrades[categoryId] || [];
    }
}
